### ISSUE TITLE
Introduce "state" status and "state" change events

### ISSUE THREAD

**Issue by trygve-lie** [podium-lib/issues#14]
During a deploy window of a podlet one might want to know in a layout that one are in such a process. One want to know that one are in a state where one are getting data from a podlet which exist in two versions due to a deploy window.

To address this we should implemented a feature which will detect what state a podlet are in. It should be something like:

 - The `@podium/client` class should have a public read only `.state` property describing a common state for all registered prodlets in use (those who have been fetched).
 - `@podium/client` class should emit a `state` event correlating with the `.state` property when the value of `.state` changes.
 - When podlets is registered but none is fetched yet the state should be `registered`.
 - When the first podlet starts fetching for the first time (the first call to the `.fetch()` or `.stream()` method of any of the registered podlets), the state should be set to `fetching`.
 - The first podlet to successfully complete a full fetch when state is `fetching`, should set the state to `updating`.
 - When the state is set to `updating` there should be set a "updating window" timeout for x seconds and a "health monitor" timeout which has a longer timeout than the timeout of the "updating window" timeout.
 - When the "updating window" timeout times out, the state should be set to `stable` and the "health monitor" timeout should be removed.
 - When one of the registered podlets detects a version change, state should be set to `updating`. This should again trigger the above timeout logics.
- If state is `updating` and one of the podlets detect a version change the "updating window" timeout time should be reset. The "health monitor" should not be altered.
- When "health monitor" timeout times out, it should remove the "updating window" timeout and set state to `unstable`.
 - If state is `unstable`, it should not be possible to enter any other state.

The above aims to address the following:

A given number of podlets is registered and fetched. Then one podlet changes due to a new deploy of the podlet. This podlet are now in two versions in production and which version the client hits is random until the old version of the podlet is gone and the new version is fully serving all requests. During this deployment window requests will jump between old and new version of the podlet. How long this window is depends on a lot of factors. What we want to know in a layout is when this window opens and when it closes.

With the above approach we detect when a deploy window startes (enters "updating" state), for every time a reqest to a podlet jumps between versions we reset the `updating` state. When this jumping between versions eases down, we wait a bit (the "updating window" timeout) and then sets state to "stable". This give us the end of a deploy window.

The above should also cater for if a podlet constantly keeps jumping between versions (ex; someone have done the error of setting the podlets version number based on a time stamp etc). The "health monitor" timeout should cater for such. In such a case we can detect that someone messed up and a human should be alerted to resolve the issue.

Code vice this should look something like this:

```js
const Client = require('@podium/client');
const client = new Client();

client.on('state', (state) => {
    if (state === 'updating') {
        // entering deploy window
    }
    if (state === 'stable') {
        // exiting deploy window
    }
});

const foo = client.register({
    name: 'foo',
    uri: 'http://foo.site.com/manifest.json',
});

const bar = client.register({
    name: 'bar',
    uri: 'http://bar.site.com/manifest.json',
});

app.use('/', async (req, res) => {
    const content = await Promise.all([
        foo.fetch(),
        bar.fetch(),
    ]);

    if (client.state === 'stable') {
        // not in a deploy window
    }

    if (client.state === 'updating') {
        // in a deploy window
    }

    if (client.state === 'unstable') {
        // one or multiple podlets is bouncing between versions
    }

    res.send('OK');
});
```

**NOTE:** The `@podium/client` does today emit a [`change`](https://github.com/podium-lib/client#change) event when a manifest changes. This will be emitted when a podlet is ex deployed as a new version. We should probably deprecate and remove this event.

**Comment by digitalsadhu** [comment]
Looks generally good, question, Is there a way to recover from `unstable` or is this essentially a terminal/ needs human input type state?

**Comment by trygve-lie** [comment]
The implemented logic ended up defering a bit from whats described above. This is the implemented logic:

The logic are now as follow:

 - The `@podium/client` class has a public read only `.state` property describing a common state for all registered prodlets in use (those who have been fetched).
 - `@podium/client` class emits a `state` event correlating with the `.state` property when the value of `.state` changes.
 - When the client is instansiated podlets is fetched yet the state is `instantiated`.
 - When the first podlet starts fetching for the first time (the first call to the `.fetch()` or `.stream()` method of any of the registered podlets), the state is set to `initializing`.
 - The first podlet to successfully complete a full fetch when state is `initializing` sets the state to `unstable`.
 - When the state is set to `unstable` there is a "unstable window" timeout for 10 seconds set and a "health monitor" timeout which has a longer timeout (4 minutes) than the timeout of the "updating window" timeout.
 - When the "updating window" timeout times out, the state is set to `stable` and the "health monitor" timeout is removed.
 - When one of the registered podlets detects a version change, state is set to `unstable`. This should again trigger the above timeout logics.
- When state is `updating` and one of the podlets detect a version change the "updating window" timeout time is reset but the "health monitor" timeout is not be altered.
- When "health monitor" timeout times out, it removes the "updating window" timeout and set state to `unhealthy`.
 - When the state is `unhealthy` the "unstable window" timeout will contiune to be set but state will be kept as `unhealthy` until a successfully `stable` state is set by the "unstable window" timeout.

>  Is there a way to recover from `unstable` or is this essentially a terminal/ needs human input type state?

In the final implementation, this is possible. Note: whats refered to in the comment as `unstable` are in the final implementation `unhealthy`.
