### ISSUE TITLE
Align metric names and give metrics some love

### ISSUE THREAD

**Issue by trygve-lie** [podium-lib/issues#17]
Currently metric names are a bit all over the place. Here is an example of what we get out of `@podium/layout` at the moment (taken from a test):

```js
expect(arr[0].name).toBe('context_run_parsers');
expect(arr[1].name).toBe('podlet_manifest_request');
expect(arr[2].name).toBe('podlet_fallback_request');
expect(arr[3].name).toBe('podlet_content_request');
expect(arr[4].name).toBe('context_run_parsers');
expect(arr[5].name).toBe('podium_proxy_request');
```

It would be good if all metrics had `podium` as a prefix to the name or as a `label`.

Currently we are also using the raw [`.metric()`](https://github.com/metrics-js/client#metricoptions) method in all methods so we are missing type info on the metrics. We should use the appropiate `.gauge()`, `.counter()` etc methods instead.

We also have a couple of places where we [decorate](https://github.com/podium-lib/client/blob/master/lib/resource.js#L12-L20) the metrics with the podlet name. This should be possible to be added on the metrics as a label everywhere where we create the metric. In other words; the podlet name should be appended where the metric is created and being set with a decorator.

**Comment by digitalsadhu** [comment]
@trygve-lie 
Do we have access to the podlet or layout names in `@podium/client`, `@podium/context` or `@podium/proxy`?

**Comment by digitalsadhu** [comment]
2 issues if we want to remove the stream decorators and add layout and podlet names where the metrics are created. 

**1.** Currently, if you mount the proxy in the podlet, metrics coming from the proxy will get decorated with the podlet name and if the proxy is mounted in the layout, metrics will decorated with the layout name which is great. This would no longer work if we did the labelling where the metrics are created unless we pass additional data into the modules such as podlet and layout name values. 

**2** As alluded to in 1. Some of the modules have no access to the podlet or layout name value internally and would need to be modified to have this information passed in.

**Comment by trygve-lie** [comment]
> Do we have access to the podlet or layout names in @podium/client, @podium/context or @podium/proxy?

Yes. [HttpIncoming](https://github.com/podium-lib/utils/blob/master/lib/http-incoming.js#L80-L82) should have it.

> 1. Currently, if you mount the proxy in the podlet, metrics coming from the proxy will get decorated with the podlet name and if the proxy is mounted in the layout, metrics will decorated with the layout name which is great. This would no longer work if we did the labelling where the metrics are created unless we pass additional data into the modules such as podlet and layout name values.

The proxy is only used in development in the podlet. It will never report metrics in production so I'm not sure how much value this is.

> As alluded to in 1. Some of the modules have no access to the podlet or layout name value internally and would need to be modified to have this information passed in.

Do you have an example?

**Comment by digitalsadhu** [comment]
Good point re: podlet name and dev. 

The proxy doesn't seem to have access to the layout name for example

**Comment by trygve-lie** [comment]
I'm fine with adding `name` to the proxy module. All other modules does take a `name` so I do not see nothing bad in adding it to the proxy either.

**Comment by digitalsadhu** [comment]
Fixed in https://github.com/podium-lib/podlet/pull/31/commits/be7a3a50c5db41c810685cc3158ea4b67b6d505f
and https://github.com/podium-lib/layout/pull/30/commits/f491cfb94f84b655d0f00e6e9ec836652324ad58

Metric names have been aligned across modules and all metrics calls use the new metrics classes to generate metrics.
