### ISSUE TITLE
Support https

### ISSUE THREAD

**Issue by trygve-lie** [podium-lib/issues#2]
Currently none of the modules support fetching stuff over https. This should be supported.

**Comment by kamkie** [comment]
we need that 

cc @eduardoinnorway

**Comment by eduardoinnorway** [comment]
@kamkie Could this be in the scope of the pilot to enhance podium-lib with https support?

**Comment by piotrjaw** [comment]
Created a pull request: https://github.com/podium-lib/client/pull/63

**Comment by trygve-lie** [comment]
Sweet. I'll take a look at the PR later today and adjust a couple of http checks to make this into a release. Will try to do a release for you with this before the weekend.

**Comment by trygve-lie** [comment]
Thanks a lot for this. Try version 4.1.2 of @podium/layout and you should find this merged :)

Let me know if there is anything. Happy to provide help and guidence.
