### ISSUE TITLE
Getting started not working

### ISSUE THREAD

**Issue by JuanGimenez** [podium-lib/issues#33]
I have just started my first project with podium, i am following the documentation and when i run the command node serve.js  it happens
![image](https://user-images.githubusercontent.com/22611924/73951932-a415b300-48fe-11ea-910f-1739272ca7ee.png)

**Comment by digitalsadhu** [comment]
Hi @JuanGimenez 

I can’t get a good sense of what’s wrong from your screenshot. 

Would you be able to provide a bit more details about what’s going wrong for you?

**Comment by trygve-lie** [comment]
Do you get any errors when you are trying to access the server from a browser? I am also not quite sure what the issue here is.

**Comment by digitalsadhu** [comment]
@JuanGimenez looking at your screenshot again, I'm wondering if maybe you just need to add a logger to get log output. If you change your layout constructor to add logger: 

```js
new Layout({
  ...
  logger: console,
  ...
});
```

Does this change anything for you?
