### ISSUE TITLE
Don't try to figure out original url our self

### ISSUE THREAD

**Issue by trygve-lie** [podium-lib/issues#34]
Currently the `HttpIncoming` object is trying to find [original url](https://github.com/podium-lib/utils/blob/master/lib/http-incoming.js#L20) based on the bare node.js request object passed in. This is a bit double work and have a couple of issues.

We should remove the usage of `original-url` and detect this by using default `.url` param in node as described here: https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_message_url

Then the `HttpIncoming` object should be able to take a value to set url instead. By doing it so, it wlll in a plain node http server (read no framework) use what node does but one can choose to provide a value from ex `original-url` if one want to. Its then up to the developer to choose, not Podium.

Then in the http frameworks we support we will pick the url value which the framework provide and set that as a value for url in `HttpIncoming`.

This should remove some double work and also make url value in podium align with the urls provided by the framework.

**Comment by digitalsadhu** [comment]
@trygve-lie can we close this one now?

**Comment by digitalsadhu** [comment]
original-url removed in podium v5
