### ISSUE TITLE
Where can I find an example with angular?

### ISSUE THREAD

**Issue by JuanGimenez** [podium-lib/issues#35]

**Comment by digitalsadhu** [comment]
We don't currently have any examples using Angular I'm afraid. How you approach this will depend on how you setup your layouts and podlets. Are you podlets likely to be publicly available or will they be private and just the layout public? If you give me a bit of information about your setup (or how you think you might set things up if you havent got anything setup yet) I'd be happy to recommend an approach to take.

**Comment by JuanGimenez** [comment]
I am new in micro frontends... I want to know if is possible use an angular component and a java component (Wicket 8)

**Comment by digitalsadhu** [comment]
@JuanGimenez 

If I understand your question correctly, then yes, it's possible.

In Podium terms, there are layouts (pages) and podlets (page fragments). A layout combines a number of podlets into a page.

It is possible for each podlet to serve up HTML and then make use of client side JavaScript written in different frameworks such React, Angular, Vue, whatever you like. You can also render HTML content with no client side JavaScript. You can even mix and match. (Though not necessarily ideal)

All this is usually done from Node.js servers (all our core libraries are written in Node.js) though it's also possible with Java or in fact any language with a little more effort. 

Where I work, we have some podlets written in Java though most are written in Node.js.

Does that answer your question? If not, feel free to provide more details about what you would want to achieve and I'll do my best to respond.

**Comment by Jozzeh** [comment]
I wrote a couple of articles on Medium about composing multiple React, VueJS & Svelte apps using Podium... Here are the links:  
React: https://medium.com/@jozzeh/react-micro-frontends-with-podium-dd832075d924   
VueJS: https://medium.com/@jozzeh/vue-micro-frontends-with-podium-7d4d96b36596   
SvelteJS: https://medium.com/@jozzeh/easy-svelte-micro-frontends-with-podium-34aa949bed02    
Mix of the above: https://medium.com/@jozzeh/react-vue-svelte-on-one-page-with-micro-frontends-f740b3ee6979   

I have combined angular with other frameworks on a page... but I don't know Angular good enough to know if it is the correct way to go.  
See the code at: https://github.com/Jozzeh/micro-frontends-divers

**Comment by digitalsadhu** [comment]
@Jozzeh these are great! Super detailed and thorough!

**Comment by Jozzeh** [comment]
Thanks! I hope it can serve as a starting point for others on how to integrate front-end frameworks/libraries with Podium. I might go a bit more in-depth about routing in the future but I'm very happy with the traction the articles are getting at the moment.
