### ISSUE TITLE
Approaches - multiple frameworks & libraries

### ISSUE THREAD

**Issue by Jozzeh** [podium-lib/issues#37]
I've gone through the docs and made a project that combines  
- Vanilla HTML
- React (using create-react-app)
- Angular (using ng cli)
- VueJS (using vue cli)
- Svelte
on 1 page and I used the messagebus to emit some messages.   
You can see it @ https://github.com/Jozzeh/micro-frontends-divers   
But I'm not sure the approach I took, is the right one.   

As it is in the repository, the podlets need to be publicly available because they serve js & css. Because front-end frameworks/libraries rely on that js & css ... Does that mean they always need to be publicly available?    

Let's say I'd like the podlets to be private... How should I approach that?  
(Copy the production css, js & images in a folder below the base-application?)   

So... I'm curious what you think about the setup.  
(It's only to demo but nevertheless, I'd like to do it "right".)

**Comment by digitalsadhu** [comment]
Hey @Jozzeh Nice setup!

One way to get your podlets private is to publish your client side assets to somewhere where they can be served on a public CDN. 

The general principal for a vanilla CDN based approach would be:
* when you make changes to your client side code, upload new versions to the CDN
* set the full CDN URLs using `podlet.js()` and `podlet.css()`

We are working on a new solution to streamline this approach called Eik, which is currently at an alpha type stage at the moment so not quite ready for primetime. Hopefully very soon.

**Comment by Jozzeh** [comment]
Thanks for having a look and giving some information.   
Maybe some people are inspired from my repository on how to integrate popular frameworks in Podium.

**Comment by Jozzeh** [comment]
I haven't closed this 'issue' because I was thinking about getting the podlets private...  
So here's my quick attempt to make podlets 'private' without using a CDN:   
https://github.com/Jozzeh/micro-frontends-private  

(The code is a bit quick & dirty... but it works. Requirements in the readme.). 
In short, the css, js & static files are defined and then copied in the base application folder in the podlets folder which is created the first time when building a micro front-end.  
Each podlet gets its own folder with: 
- podlet.js 
- css (css files for the podlet)
- js (js files for the podlet)
- static (static files, these folders are served with express static)  

I'm interested in what you think, even though filesystem actions are usually for 'operations' or DevOps...     

Also, I'd like to document how I integrated each library/framework in podium (see first post), and I was thinking about writing an article about it on Medium for example.   
May I write an article? or rather not?

**Comment by trygve-lie** [comment]
Hi there

Podlets do not need to be publicly available (they can). We do actually recommend them to not be. What we do at FINN.no (where both me and @digitalsadhu work and where we use Podium at scale) is that Layout servers are publicly available and Podlets are not. 

How we achieve this is by infrastructure where public access to the Layout servers is opened in the firewall. 

Then there is the issue that Podlets do have assets (js, css, images, fonts etc) and API endpoints (XHR and form POST requests etc) which needs to be accessed from the browser which loaded the html document the Layout composed and served. 

For cases where the browser needs to do a XHR or form POST back to the podlet you will need to take use of the built in proxy feature in Podium. The proxy feature is there exactly for the case of catering for the need to have Layouts publicly available while Podlets are private.

Here at FINN each Podlet uploads its assets to a CDN which serve these assets but if you do not want to or are not able to use a CDN, you can use the built in proxy to make the assets in podlets publicly available. To do so you just need to define the path or your static endpoint in each Podlet as a proxy endpoint. Please take a look at: https://podium-lib.io/docs/api/podlet#proxy-target-name- 

> Also, I'd like to document how I integrated each library/framework in podium (see first post), and I > was thinking about writing an article about it on Medium for example.
> May I write an article? or rather not?

Sure. Feel free to do so :)

**Comment by Jozzeh** [comment]
Thanks (for not shouting RTFM),  
I'll definitely have a look at the proxy and try it out!  
The setup I made in the 'private' repo is an attempt to remove the need for a CDN. But it takes away some micro frontend advantages.
