### ISSUE TITLE
Podlet asset reset

### ISSUE THREAD

**Issue by natoehv** [podium-lib/issues#40]
Hi Everyone!, I'm working on a nuxt module to Podium-lib, a I found the next problem, I use the `render:resourcesLoaded` hooks on nuxt to fill the podlet assets, and in development mode this fire every time with hotreload, so I put the same resources every time, and the podlet doesn't has validation or a reset to inject again:

```
this.nuxt.hook('render:resourcesLoaded', ({clientManifest} : any) => {
    if (clientManifest) {
      const { all, publicPath } = clientManifest;
      const filter = (type: string) => (asset: string) => asset.split('.')[asset.split('.').length - 1] === type;
      const filteredJS = all.filter(filter('js'));
      const filteredCSS = all.filter((filter('css'));
      podlet.js(filteredJS.map((asset: string) => ({
        value: publicPath + asset,
        defer: true,
      })))
      podlet.css(filteredCSS.map((asset: string) => ({
        value: publicPath + asset,
      })))
    }
  });
```

for now I had to create a custom validation, but doesn't work en case where I need to delete unused asset:

````
this.nuxt.hook('render:resourcesLoaded', ({clientManifest} : any) => {
    if (clientManifest) {
      const { all, publicPath } = clientManifest;
      const filter = (type: string) => (asset: string) => asset.split('.')[asset.split('.').length - 1] === type;
      const filterInto = (compare: string[]) => (asset: string) => !compare.find(val => val === asset);
      const filteredJS = all.filter(filter('js')).filter(filterInto(podiumJS));
      const filteredCSS = all.filter(filter('css')).filter(filterInto(podiumCSS));
      podiumJS = Object.assign(podiumJS, filteredJS);
      podiumCSS = Object.assign(podiumCSS, filteredCSS);
      podlet.js(filteredJS.map((asset: string) => ({
        value: publicPath + asset,
        defer: true,
      })))
      podlet.css(filteredCSS.map((asset: string) => ({
        value: publicPath + asset,
      })))
    }
  });
```

is it possible to add an extra function to reset podlet resources?

**Comment by natoehv** [comment]
here is the module to use Podium podlets with nuxtjs https://github.com/natoehv/nuxt-podium-module

**Comment by digitalsadhu** [comment]
This is something I recall discussing at some point though we haven't made any decisions or landed on anything as of yet.
@trygve-lie may have something to add.

**Comment by digitalsadhu** [comment]
Out of interest, what's your setup like using Nuxt? You can have a Nuxt layout and a number of Nuxt podlets etc?

**Comment by natoehv** [comment]
yep, but the layout is just `nodejs` + podium layout (for now) and the Podlets are built based on `Nuxtjs`. so each `nuxt-podlet` can decide if use SSR or just CSR (using the Nuxt tools).

**Comment by digitalsadhu** [comment]
It's also worth noting that you can actually reset the assets using the non documented internal properties jsRoute and cssRoute.

Eg. This will reset the internal asset arrays

```js
podlet.jsRoute = [];
podlet.cssRoute = [];
```
