### ISSUE TITLE
Providing auth context to a Podlet

### ISSUE THREAD

**Issue by jameswragg** [podium-lib/issues#42]
Hi first off, thank you so much for creating this library! Having read through some docs and having a poke about its getting me quite excited as to the possibilities. Especially as it comes with integration for Hapi.js out of the box! 👌

I have a layout server that authenticates users, I'd like to pass that auth object (from hapi) on to the podlets so they can be aware of logged-in state.

I saw I could pass querystrings in the `.fetch(ctx, { query: {} })` so initially thought I could POST to the podlet with a payload but seems that a custom context parser may be what I need? The [docs there are a little sparse](https://podium-lib.io/docs/layout/context#custom-context-parsers) here so not sure.

Any direction you can give would be appreciated, thanks.

**Comment by digitalsadhu** [comment]
Hey @jameswragg !

It is indeed as you say, you have 2 choices, you can either pass things from the layout to the podlet during the fetch call using query parameters or you can write a custom parser to add your values to the Podium context. The use case you are describing sounds to me like a custom context parser might be the right choice perhaps. 

The docs do look a bit sparse in this case I see, but you can register a new context parser by giving the context register method an object with a `parse` method like so:

```js
class Parser {
  async parse(incoming) { // can be async (or not)
    // do something with the values on the Podium incoming object
    // return some value to be included
  }
}

const parser = new Parser();
layout.context.register('customParser', parser);
```

Then when the context is serialised, the header `podium-custom-parser` will also be sent.

Take a look at our internal parsers for inspiration
https://github.com/podium-lib/context/tree/master/lib

Hope that helps!

**Comment by jameswragg** [comment]
Thanks for the reply @digitalsadhu!

How would I get request-time data into that parser? e.g. the hapi framework has already parsed route params/cookies/auth data etc. etc. & its that data I'd like to pass along with the `.fetch()`? This customParser only seems to have access to the raw request or am I missing something fundamental here?

Thanks in advance!

**Comment by jameswragg** [comment]
I got the custom parsers/context working, thanks for your help @digitalsadhu.

Digging a little deeper, I see the incoming request (and custom parsers) are populated by Podium in the `onRequest` hook[1] of hapi, which is at the very beginning of the [request lifecycle](https://futurestud.io/files/hapi/hapi-request-lifecycle.pdf) & before the framework has processed the incoming request. This means I'm struggling to see how to pass route params, cookie/state or any other data thats available in the layouts route handler to a podlet.

Any help appreciated.

[1] https://github.com/podium-lib/hapi-layout/blob/master/lib/layout-plugin.js#L38

**Comment by jameswragg** [comment]
Ended up with the following which feels a little peculiar but seems to work.

```
// snip

layout.context.register("auth", {
  async parse() {
    return "";
  },
});

server.route({
  method: ["GET", "POST"],
  path: layout.pathname(),
  handler: async (request, h) => {
    const incoming = request.app.podium;

    incoming.context["podium-auth"] = JSON.stringify(request.auth);

    const response = await headerPodlet.fetch(incoming);

    return layout.render(incoming, response);
  },
});

```

Out of interest what is the reasoning behind data being passed via HTTP headers, rather than via a regular POST?

**Comment by digitalsadhu** [comment]
Using headers and/or query params allows us to send data to a podlet in the same request as we fetch its response. Usually if you have some post/patch/delete requirements, you'd set up another route and potentially use Podium's proxy feature. In your case here though it seems like you just need to fetch the Podlets content to include in your page and in order to do so you need to provide authentication so it seems to me like you are on the right track. 

As for the lifecycle issue with Hapi, maybe @trygve-lie can chime in here?

**Comment by jameswragg** [comment]
Sorry for the delay @digitalsadhu. I see now how you have to `register()` a namespace on the layout context, populate it in the layout route handler for it to then to be available in the Podlet route handler context. I'm slowly getting there & now understand why the hapi plugin is where it is (you populate context in the handler).

Please correct me if any of this is wrong!

**Comment by jameswragg** [comment]
I’m trying to build a shared header Podlet. This Podlet service must reflect things like auth state, branding & reflect client menu configuration.

I have the auth state, client ID and config already in the existing layout server. I was trying to pass auth context and a payload for the Podlet to use in its render, a little like an API receiving a JSON payload but I think this is possibly an anti-pattern with micro front-ends, in that the podlet should be independent?

So I'm considering the need for some kind of shared session storage, passing a client ID + session ID in the Podium context for the Podlet to pickup and make the API calls itself for config etc. or would you suggest I try to pass along the incoming cookies header on the layout server to the Podlet to parse & use as per the layout server?

Would appreciate the benefit of your experience here, thanks in advance.

**Comment by jameswragg** [comment]
I ended up passing auth context to the podlet via custom Podium context (HTTP headers).
