### ISSUE TITLE
How to serve Podlet assets via public Layout proxy?

### ISSUE THREAD

**Issue by jameswragg** [podium-lib/issues#44]
I have a private Podlet server (`podlet.internal:9001`) called `header` that has CSS and JS assets, I want these to be served via the public Layout server (`mywebsite.com`) using the proxy but I don't want to hardcode the public/layout server path in my podlet.

Can this path be generated automatically? As I'm currently facing this issue:

I add the podlet assets with:
```
podlet.css({ value: "/public/css/styles.css" });
podlet.js({ value: "/public/js/index.js" });
```

I setup a proxy in the Podlet to inform the Layout server:
```
podlet.proxy({ target: "/public", name: "public" })
```

And I get this in my layout server (error - server unreachable):
```
<link href="http://podlet.internal:9001/public/css/styles.css" type="text/css" rel="stylesheet">
<script src="http://podlet.internal:9001/public/js/index.js"></script>
```

Instead of the desired:
```
<link href="http://mywebsite.com/podium-resource/header/public/css/styles.css" type="text/css" rel="stylesheet">
<script src="http://mywebsite.com/podium-resource/header/public/js/index.js"></script>
```

How do I get the layout server to use the correct (self-proxied) URLs for the Podlet assets?

**Comment by jameswragg** [comment]
Rewrote the issue to hopefully explain a little better.

**Comment by digitalsadhu** [comment]
@trygve-lie will correct me if I'm wrong but I don't think we've considered using the proxy mechanism for the client side asset files before. 

We generally recommend that the podlet publish its assets to a cdn and then put the url for the cdn into the manifest file thereby offloading the burden of serving files from the podlet.

As things stand, could what you are asking be done... hmm... not at the podlet only level I don't think. You'd have to do it in the layout as part of the fetch process where you could massage the urls.

**Comment by jameswragg** [comment]
I took a proxy for assets pointer from @trygve-lie here https://github.com/podium-lib/issues/issues/37#issuecomment-624654070

I tried manipulating the URLs after the fetch but seems the PodiumResources really want to be read-only.

Ended up constructing the URLs in the template but assets are now proxied & served by the podlet servers now!
