### ISSUE TITLE
Does MessageHub work when using scaled NodeJS servers?

### ISSUE THREAD

**Issue by jmrozak** [podium-lib/issues#46]
Look at this scenario:

1. My application has two Layout NodeJS server, two NodeJS servers for PodletA and three NodeJS servers for PodletB.
2. The Layout servers are served from behind a load balancer.
2. The PodletA servers are also served from behind a load balancer.  
3. Ditto for PodletB servers.
4. If Layout uses MessageBus to talk to any of the Podlets, or if a PodletA server wishes to talk to a PodletB server, the load balancer(s) will be "in the middle".

**This is the question:**  does MessageBus transparently work with Podlet servers that are behind load balancers?  Or does sending a message to a PodletB server expect only one particular server, with a possibly fatal result?

For example, suppose that the PodletA talks at 10:00:01 AM with a PodletB through the bus, and got a response.  At 10:00:03 AM it wants to ask another question of PodletB.  But in the meantime, at 10:00:02 AM the original NodeJS instance has been killed by the load balancer which created a replacement.  What happens -- the conversation is successful, or fails?

**Comment by jameswragg** [comment]
@jmrozak MessageBus is purely a client-side comms channel. Any events fired onto the channel can be listened for by any consumer.

An example may be PodletA provides the page header inc. checkout basket item count. It has a JS file that uses MessageBus to subscribe to any `cart:add` events that are fired on the page, when the event is heard the item count increases & DOM updated.
PodletB may provide the shopping catalog. It has a JS file that uses the MessageBus and fires a `cart:add` event with the item ID when then "Add to cart" button is pressed.

When building multiple micro front-ends you don't want to couple them together to allow independent development. This MessageBus is a method of providing a loose coupling.

**Comment by digitalsadhu** [comment]
Closing as well answered by @jameswragg, thanks!
