### ISSUE TITLE
Is this project alive? (Answer: Yes absolutely!)

### ISSUE THREAD

**Issue by eugef** [podium-lib/issues#48]
Hi guys, first of all my kudos for such a great project. 

The core concept behind it is very appealing to me so I want to try it out.
But i've noticed that the last meaningful update was in August 2019 and since that time this project feels a bit abandoned.

Are you guys still considering to move forward with it? Or it doesn't make sense for me to use it in my projects anymore?

**Comment by digitalsadhu** [comment]
This project is far far far from abandoned, it is in fact supported and used extensively by Norway's largest marketplace https://finn.no. We have close to 200 Podium micro-frontend apps running in production today and this number continues to grow. Both @trygve-lie and myself work on the team with the responsibility for supporting, maintaining and growing the Podium project so we get dedicated time during our day to day for the project.

And while it has grown pretty mature at this point, you can:

* rest assured that if any security issues come up, they'll be patched right away
* expect new features in the not too distant future once we finish with a few other pressing projects.

Thanks for your interest!

**Comment by eugef** [comment]
Hi @digitalsadhu, thanks for your reply.
