### ISSUE TITLE
Does it work nicely with Webpack Module Federation?

### ISSUE THREAD

**Issue by eugef** [podium-lib/issues#49]
What are your ideas/opinions about using Podium together with Webpack Module Federation?

WMF is a great solution to do client-side runtime composition of micro-frontends, while Podium does it server-side. So i wonder if they can work nicely together.

**Comment by robertovg** [comment]
This is a great question, are those technologies compatible?

**Comment by botoxparty** [comment]
Module federation is not strictly client-side, it can also be used server-side.

**Comment by digitalsadhu** [comment]
We haven't looked at this at all. We use another OS project we created for our client side assets https://eik.dev so thats are main focus. If someone looks into this, let us know!
