### ISSUE TITLE
node16 aborted ECONNRESET network error from `request`

### ISSUE THREAD

**Issue by ghost** [podium-lib/issues#51]
Hi,

Thanks very much for building podium!

I've encounted an issue which i've traced back to a network error in `request` library failing in node16. I can repeat the same request which succeeds with a different http client. The message im getting is `Error reading content at podlet-url: aborted`, which originates from [here](https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/request.js#L1079). I switch to node14 and it fixes it.

I'm sorry i don't have a reproducable example yet, but my steps were as follows:
- run my hapi server with `@podium/client@4.5.15` on node16
- fetch my podlet content (works!)
- deploy a new version of podlet (new version number in manifest) to my aws environment
- try to fetch podlet again, but encounter the `aborted ECONNRESET` issue above
- try these steps with node14, and I don't encouter this issue

Even ignoring my error, may I suggest replacing `request` as its been [deprecated for some time](https://github.com/request/request/issues/3142). Perhaps with [got](https://github.com/sindresorhus/got) or similar library?

Thanks.

**Comment by trygve-lie** [comment]
Thanks for reporting this. 

First of all; we are fully aware that request is not recommended for use and our plan is soon to switch to using [undici](https://github.com/nodejs/undici). Undici is modern, a lot faster and will be shipped in node.js from version 18.x. I hope to start working on replacing request with undici pretty soon actually.

We do run a good amount of node 16 here at FINN.no and have not seen this error (yet). Though we do see the `ECONNRESET` message from time to time when a podlet happen to respond too slow. The time out of requests in a layout server is set pretty low so could you try to increase the timeout of the requests to your podlets?

You do so by setting the timeout property on the options object to the client for each podlet you register in the layout: https://podium-lib.io/docs/api/layout#options-required

**Comment by ghost** [comment]
Extremely late update!

So we're upgrading our node versions now, I've had another go at debugging this issue.

On node16+, it is triggered when a podlet manifest version changes (where it will try to get a fresh version of stuff), and fails if the podlet response is large enough (in my example, 64k ish?)

See example project: https://github.com/RichPMad/podium-client-podlet-abort 

At first I thought it was the way node change handling aborting a request/response. Node14 function https://github.com/nodejs/node/blob/v14.x/lib/_http_client.js#L431 vs Node16 calls `res.destroy(connResetException('aborted'));` https://github.com/nodejs/node/blob/v16.x/lib/_http_client.js#L454 .

But now I don't know what to think!

Thanks for any help you can provide.

**Comment by rphippswiley** [comment]
As you can see I turned in to a ghost user, this is my badly migrated user account :D 

I tested version 5 of podium client, and it does not suffer from this bug. Added a test for that in the example https://github.com/rphippswiley/podium-client-podlet-abort . The bad news is for us is, to use this version, we would have to migrated our entire codebase from cjs to esm.

**Comment by rphippswiley** [comment]
Oh! did you fix this with https://github.com/podium-lib/client/commit/a41f44a6c4aff7aec8201d05ce220dbdbb648cfd ?

**Comment by digitalsadhu** [comment]
Yes, this is resolved in Podium v5.
