### ISSUE TITLE
Update documentation site to Docusaurus version 2

### ISSUE THREAD

**Issue by trygve-lie** [podium-lib/issues#56]
The documentation site is built with Docusaurus. Update Docusaurus to [version 2 pre release](https://docusaurus.io/docs/next). 

Currently the documentation site has to be built and deployed manually. This should be done automatically upon merge of PRs to the `source` branch. The setup for this in the Eik project can probably just be copied into here: https://github.com/eik-lib/eik-lib.github.io/blob/source/.github/workflows/deploy-doc.yml

**Comment by digitalsadhu** [comment]
Done
