### ISSUE TITLE
combining layout and podlet assets

### ISSUE THREAD

**Issue by mingfang** [podium-lib/issues#59]
Should the Layout automatically combine layout and podlet assets?
I'm not seeing the combined assets and I'm not sure if it's a bug.
I have to manually combine the assets like this
```javascript
app.get(layout.pathname(), async (req, res) => {
  const incoming = res.locals.podium
  const content = await podlet.fetch(incoming, {query: req.query})
  incoming.js.push(...content.js)
  incoming.css.push(...content.css)
  res.podiumSend(`<div>podlet: ${content}</div>`)
})
```

Is this a bug?

**Comment by digitalsadhu** [comment]
To combine, you need to set the podlet response on incoming like so:

```js
incoming.podlets = [content]
```

Normally you would use Promise.all to fetch several podlets at once and then set the response of that. 

```js
const result = Promise.all(…)
incoming.podlets = result
```

**Comment by mingfang** [comment]
@digitalsadhu 
Thanks; you suggestion works. 
Also, for anyone looking, I was able to find this documented here https://podium-lib.io/docs/api/assets
