### ISSUE TITLE
Multiple instances/version conflicts with React? Shared dependency management?

### ISSUE THREAD

**Issue by botoxparty** [podium-lib/issues#61]
Hey!

I've been playing around with podium using some React podlets. I was wondering how multiple versions/instances of React are supported with podium? And how shared dependencies are managed in general? e.g. components from a design system.

I couldn't find anything in the documentation regarding this topic. Hopefully someone has some experience around this.

**Comment by digitalsadhu** [comment]
Hey, we wrote another project to solve our various client side asset needs with Podium. It’s called Eik and you can find it here. https://eik.dev/
We use Eik to line up versions of libraries like React across Podium podlets and layouts.

**Comment by botoxparty** [comment]
Thanks for the super fast response!

Will definitely check out Eik.

**Comment by digitalsadhu** [comment]
You’re welcome ☺️
