### ISSUE TITLE
Client response inspect

### ISSUE THREAD

**Issue by digitalsadhu** [podium-lib/issues#62]
It looks like the next branch contains an incorrect inspect definition on the Response class.

On main, the definition is:

```js
[util.inspect.custom](depth, options) {
    return util.inspect(this.toJSON(), depth, options);
}
```
See: https://github.com/podium-lib/client/blob/f47c2a24ae923c0a8db176d13c35277c17e305fd/lib/response.js#L71-L73

But on next, this has been changed to:

```js
[inspect]() {
      return {
            referrerpolicy: this.referrerpolicy,
            crossorigin: this.crossorigin,
            integrity: this.integrity,
            nomodule: this.nomodule,
            value: this.value,
            async: this.async,
            defer: this.defer,
            type: this.type,
            data: this.data,
      };
}
```
See: https://github.com/podium-lib/client/blob/68ef10cb9324d190dc05360e9f911f4c3e012d23/lib/response.js#L61-L73

This seems like an inspect definition that belongs on the AssetCss and AssetJs util classes.
Ok if I change this back @trygve-lie ?

**Comment by trygve-lie** [comment]
Good catch. This sure is wrong.
